name: backend
channels:
  - anaconda
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - expat=2.6.3
  - krb5=1.20.1
  - libcxx=14.0.6
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libmpdec=4.0.0
  - libpq=12.20
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - postgresql=12.20
  - python=3.13.0
  - python_abi=3.13
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - astroid==3.3.5
      - blinker==1.8.2
      - boto3==1.36.26
      - botocore==1.36.26
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - dill==0.3.9
      - flask==3.0.3
      - flask-cors==5.0.0
      - flask-jwt-extended==4.6.0
      - flask-sqlalchemy==3.1.1
      - gunicorn==23.0.0
      - idna==3.10
      - isort==5.13.2
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jmespath==1.0.1
      - markupsafe==3.0.2
      - mccabe==0.7.0
      - packaging==24.2
      - platformdirs==4.3.6
      - psycopg2==2.9.10
      - pycodestyle==2.12.1
      - pyjwt==2.9.0
      - pylint==3.3.1
      - python-dateutil==2.9.0.post0
      - requests==2.32.3
      - s3transfer==0.11.2
      - six==1.17.0
      - sqlalchemy==2.0.36
      - tomlkit==0.13.2
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - vulture==2.13
      - werkzeug==3.1.1
prefix: /opt/miniconda3/envs/backend
